# the energy cutoffs are specified in Rygbergs
pslibrary_1_0_0 = [
    {'element': 'Ag', 'accuracy': 'low', 'filename': 'Ag.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 180},
    {'element': 'Al', 'accuracy': 'low', 'filename': 'Al.pbesol-nl-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 29, 'min_ecutrho': 121},
    {'element': 'Ar', 'accuracy': 'low', 'filename': 'Ar.pbesol-nl-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 46, 'min_ecutrho': 189},
    {'element': 'As', 'accuracy': 'low', 'filename': 'As.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 20, 'min_ecutrho': 103},
    {'element': 'At', 'accuracy': 'high', 'filename': 'At.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 50, 'min_ecutrho': 471},
    {'element': 'Au', 'accuracy': 'low', 'filename': 'Au.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 41, 'min_ecutrho': 529},
    {'element': 'Ba', 'accuracy': 'high', 'filename': 'Ba.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 37, 'min_ecutrho': 176},
    {'element': 'Be', 'accuracy': 'low', 'filename': 'Be.pbesol-sl-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 70, 'min_ecutrho': 710},
    {'element': 'Bi', 'accuracy': 'high', 'filename': 'Bi.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 455},
    {'element': 'B', 'accuracy': 'high', 'filename': 'B.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 43, 'min_ecutrho': 324},
    {'element': 'Br', 'accuracy': 'low', 'filename': 'Br.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 49, 'min_ecutrho': 196},
    {'element': 'Ca', 'accuracy': 'high', 'filename': 'Ca.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 274},
    {'element': 'Cd', 'accuracy': 'low', 'filename': 'Cd.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 37, 'min_ecutrho': 638},
    {'element': 'Ce', 'accuracy': 'low', 'filename': 'Ce.pbesol-spdn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 37, 'min_ecutrho': 179},
    {'element': 'Cl', 'accuracy': 'low', 'filename': 'Cl.pbesol-nl-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 182},
    {'element': 'Co', 'accuracy': 'low', 'filename': 'Co.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 238},
    {'element': 'C', 'accuracy': 'high', 'filename': 'C.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 40, 'min_ecutrho': 325},
    {'element': 'Cs', 'accuracy': 'low', 'filename': 'Cs.pbesol-spnl-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 35, 'min_ecutrho': 173},
    {'element': 'Cu', 'accuracy': 'low', 'filename': 'Cu.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 45, 'min_ecutrho': 236},
    {'element': 'Dy', 'accuracy': 'low', 'filename': 'Dy.pbesol-spdn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 36, 'min_ecutrho': 265},
    {'element': 'Er', 'accuracy': 'low', 'filename': 'Er.pbesol-spdn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 37, 'min_ecutrho': 265},
    {'element': 'Eu', 'accuracy': 'low', 'filename': 'Eu.pbesol-spdn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 35, 'min_ecutrho': 259},
    {'element': 'Fe', 'accuracy': 'low', 'filename': 'Fe.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 46, 'min_ecutrho': 237},
    {'element': 'F', 'accuracy': 'high', 'filename': 'F.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 49, 'min_ecutrho': 196}

]

