# the energy cutoffs are specified in Rygbergs
pslibrary_1_0_0 = [
    {'element': 'Ag', 'accuracy': 'high', 'filename': 'Ag.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 63, 'min_ecutrho': 408},
    {'element': 'Al', 'accuracy': 'high', 'filename': 'Al.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 30, 'min_ecutrho': 144},
    {'element': 'Ar', 'accuracy': 'high', 'filename': 'Ar.pbesol-n-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 48, 'min_ecutrho': 225},
    {'element': 'As', 'accuracy': 'high', 'filename': 'As.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 43, 'min_ecutrho': 288},
    {'element': 'At', 'accuracy': 'high', 'filename': 'At.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 50, 'min_ecutrho': 471},
    {'element': 'Ba', 'accuracy': 'high', 'filename': 'Ba.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 37, 'min_ecutrho': 176},
    {'element': 'Be', 'accuracy': 'high', 'filename': 'Be.pbesol-s-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 81, 'min_ecutrho': 870},
    {'element': 'Li', 'accuracy': 'high', 'filename': 'Li.pbesol-s-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 102, 'min_ecutrho': 414},
    {'element': 'Co', 'accuracy': 'high', 'filename': 'Co.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 74, 'min_ecutrho': 474},
    {'element': 'Zr', 'accuracy': 'high', 'filename': 'Zr.pbesol-spn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 46, 'min_ecutrho': 267},
    {'element': 'Ge', 'accuracy': 'high', 'filename': 'Ge.pbesol-dn-rrkjus_psl.1.0.0.UPF', 'type': 'ultrasoft',
    'xc': 'PBESOL', 'url': 'http://www.qe-forge.org/gf/download/frsrelease/147/493/pslibrary.1.0.0.tar.gz',
    'pslibrary': 'pslibrary.1.0.0', 'relativistic:': True, 'min_ecutwfc': 42, 'min_ecutrho': 239}
]

