# Copyright (C) 2013 - Zhongnan Xu
"""This module contains the names of all of the psuedo potential files one
needs to use. If you wish to change the directory the files are found in,
edit the ESPRESSORC dictionary file found in espressorc.py
"""

ESPRESSO_PPs = {'Ag': ('Ag.UPF', 20),
                'Al': ('Al.UPF', 3),
                'As': ('As.UPF', 5),
                'Au': ('Au.UPF', 11),
                'Ba': ('Ba.UPF', 10),
                'Be': ('Be.UPF', 4),
                'Bi': ('Bi.UPF', 14),
                'B': ('B.UPF', 3),
                'Br': ('Br.UPF', 7),
                'Ca': ('Ca.UPF', 10),
                'Cd': ('Cd.UPF', 11),
                'Cl': ('Cl.UPF', 7),
                'Co': ('Co.UPF', 16),
                'C': ('C.UPF', 4),
                'Cr': ('Cr.UPF', 13),
                'Cs': ('Cs.UPF', 9),
                'Cu': ('Cu.UPF', 18),
                'Fe': ('Fe.UPF', 15),
                'F': ('F.UPF', 7),
                'Ga': ('Ga.UPF', 20),
                'Ge': ('Ge.UPF', 14),
                'Hf': ('Hf.UPF', 10), #'hf_pbe_plus4_v1.uspp.F.UPF' alt
                'Hg': ('Hg.UPF', 12),
                'H': ('H.UPF', 1),
                'In': ('In.UPF', 11),
                'I': ('I.UPF', 7),
                'Ir': ('Ir.UPF', 15),
                'K': ('K.UPF', 8),
                'La': ('La.UPF', 11),
                'Li': ('Li.UPF', 3),
                'Mg': ('Mg.UPF', 10),
                'Mn': ('Mn.UPF', 14),
                'Mo': ('Mo.UPF', 14),
                'Na': ('Na.UPF', 9),
                'Nb': ('Nb.UPF', 13),
                'Ni': ('Ni.UPF', 16),
                'N': ('N.UPF', 5),
                'O': ('O.UPF', 6),
                'Os': ('Os.UPF', 16),
                'Pb': ('Pb.UPF', 14),
                'Pd': ('Pd.UPF', 16),
                'P': ('P.UPF', 5),
                'Pt': ('Pt.UPF', 16),
                'Rb': ('Rb.UPF', 9),
                'Re': ('Re.UPF', 15),
                'Rh': ('Rh.UPF', 15),
                'Ru': ('Ru.UPF', 15),
                'Sb': ('Sb.UPF', 14),
                'Sc': ('Sc.UPF', 11),
                'Se': ('Se.UPF', 6),
                'Si': ('Si.UPF', 4),
                'Sn': ('Sn.UPF', 13),
                'S': ('S.UPF', 6),
                'Sr': ('Sr.UPF', 10),
                'Ta': ('Ta.UPF', 13),
                'Tc': ('Tc.UPF', 14),
                'Te': ('Te.UPF', 6),
                'Ti': ('Ti.UPF', 11),
                'Tl': ('Tl.UPF', 13),
                'V': ('V.UPF', 13),
                'W': ('W.UPF', 14),
                'Y': ('Y.UPF', 11),
                'Zn': ('Zn.UPF', 20),
                'Zr': ('Zr.UPF', 12)}    
